spring:
  datasource:
    mysql:    ### 数据源1mysql配置
      jdbc-url: jdbc:mysql://  :3106/edge?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      username:
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

